#ifndef CONCUSQL_CONSTANTS_H
#define CONCUSQL_CONSTANTS_H

#define NAME_SIZE 60
#define ADDRESS_SIZE 120
#define PHONE_SIZE 13

#define SERVER_ID   1

#define SERVER_TEMPORAL "server.tmp"


#endif //CONCUSQL_CONSTANTS_H
